env: pursuit

env_args:
  n_agents: 20
  n_preys: 10
  episode_limit: 30
  map_size: 10
  catch_reward: 1
  catch_fail_reward: -1
  sight_range: 2
  obs_last_action: False
  state_last_action: True

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 4005000
test_interval: 10000
test_nepisode: 300
test_greedy: True