env: toygame

env_args:
  n_groups: 5
  n_agents_in_group: 3
  episode_limit: 1

learner_log_interval: 1000
log_interval: 1000
runner_log_interval: 1000
t_max: 500000
test_interval: 1000
test_nepisode: 32
test_greedy: True

